# Generated by Django 4.2.15 on 2024-08-23 04:39

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0002_alter_uservote_restaurant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votehistory',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='votehistory',
            name='vote_type',
            field=models.CharField(choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third')], default='exit', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='uservote',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='uservote',
            unique_together={('user', 'restaurant', 'vote_type', 'date')},
        ),
    ]
