# Generated by Django 4.2.15 on 2024-08-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_votehistory_options_votehistory_vote_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votehistory',
            name='vote_type',
            field=models.CharField(max_length=10),
        ),
    ]
