# Generated by Django 4.2.15 on 2024-08-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_votehistory_vote_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='votehistory',
            name='total_votes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='votehistory',
            name='vote_type',
            field=models.CharField(choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third')], max_length=10),
        ),
    ]
