# Generated by Django 4.2.15 on 2024-08-23 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_votehistory_total_votes_alter_votehistory_vote_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votehistory',
            name='total_votes',
        ),
    ]
